Time::DATE_FORMATS[:hrs_and_mins] = '%H:%M'
Time::DATE_FORMATS[:booking_meridian] = '%d %B %Y %l.%M%P'
Time::DATE_FORMATS[:booking] = '%d %B %Y %k:%M'
Date::DATE_FORMATS[:uk] = '%d %B %Y'
DateTime::DATE_FORMATS[:booking] = '%d %B %Y %H:%M'
DateTime::DATE_FORMATS[:booking_meridian] = '%d %B %Y %l.%M%P'
